# Generated by Django 6.0.3 on 2026-04-20 15:39

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguredForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('form_type', models.CharField(choices=[('', '')], max_length=100, verbose_name='form type')),
            ],
            options={
                'verbose_name': 'configured form',
                'verbose_name_plural': 'configured forms',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('related_object_id', models.CharField(blank=True, max_length=255)),
                ('configured_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='testapp.configuredform')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='related content type')),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Data is saved using this name. Changing it may result in data loss. This field only allows a-z, 0-9 and _ as characters.', max_length=50, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', message='Enter a value consisting only of lowercase letters, numbers and the underscore.')], verbose_name='name')),
                ('label', models.CharField(max_length=1000, verbose_name='label')),
                ('is_required', models.BooleanField(default=True, verbose_name='is required')),
                ('help_text', models.CharField(blank=True, max_length=1000, verbose_name='help text')),
                ('type', models.CharField(editable=False, max_length=1000, verbose_name='type')),
                ('choices', models.TextField(help_text='Enter one choice per line. You may optionally provide the value and the label separated by a pipe symbol (|).', verbose_name='choices')),
                ('placeholder', models.CharField(blank=True, max_length=1000, verbose_name='placeholder')),
                ('default_value', models.CharField(blank=True, help_text='Optional default value of the field.', max_length=1000, verbose_name='default value')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='max length')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='testapp.configuredform')),
            ],
            options={
                'verbose_name': 'form field',
                'verbose_name_plural': 'form fields',
            },
        ),
        migrations.CreateModel(
            name='SimpleField_checkbox',
            fields=[
            ],
            options={
                'verbose_name': 'checkbox field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_checkbox-select-multiple',
            fields=[
            ],
            options={
                'verbose_name': 'multiple checkboxes',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_date',
            fields=[
            ],
            options={
                'verbose_name': 'date field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_email',
            fields=[
            ],
            options={
                'verbose_name': 'email address field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_integer',
            fields=[
            ],
            options={
                'verbose_name': 'integer field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_radio',
            fields=[
            ],
            options={
                'verbose_name': 'radio input field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_select',
            fields=[
            ],
            options={
                'verbose_name': 'dropdown field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_select-multiple',
            fields=[
            ],
            options={
                'verbose_name': 'select multiple',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_text',
            fields=[
            ],
            options={
                'verbose_name': 'text field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_textarea',
            fields=[
            ],
            options={
                'verbose_name': 'multiline text field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='SimpleField_url',
            fields=[
            ],
            options={
                'verbose_name': 'URL field',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.simplefield',),
        ),
        migrations.CreateModel(
            name='FormStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('identifier', models.CharField(blank=True, verbose_name='identifier')),
                ('configured_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testapp.configuredform')),
            ],
            options={
                'verbose_name': 'form step',
                'verbose_name_plural': 'form steps',
                'ordering': ['ordering'],
                'abstract': False,
                'unique_together': {('configured_form', 'identifier'), ('configured_form', 'ordering')},
            },
        ),
    ]
