# Generated by Django 6.0.3 on 2026-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_richtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuredform',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
