# Generated by Django 5.2.14 on 2026-05-07 18:07

import django.db.models.deletion
from django.db import migrations, models

import feincms3_formbuilder.notifications


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_configuredform_created_at_configuredform_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuredform',
            options={'ordering': ['-created_at'], 'verbose_name': 'configured form', 'verbose_name_plural': 'configured forms'},
        ),
        migrations.CreateModel(
            name='FormNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(max_length=500, validators=[feincms3_formbuilder.notifications.validate_recipients], verbose_name='recipients')),
                ('subject', models.CharField(max_length=500, verbose_name='subject')),
                ('body', models.TextField(help_text='HTML. Supports {{ form_data.<field_name> }} and any keys the project places in the notification context.', verbose_name='body')),
                ('configured_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='testapp.configuredform')),
            ],
            options={
                'verbose_name': 'form notification',
                'verbose_name_plural': 'form notifications',
                'abstract': False,
            },
        ),
    ]
