# Generated by Django 5.2.18 on 2026-10-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_formstep_back_label_formstep_next_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplefield',
            name='show_when_field',
            field=models.CharField(blank=True, help_text='Name of the dropdown or radio field controlling this field. Leave empty to always show this field.', max_length=50, verbose_name='show when field'),
        ),
        migrations.AddField(
            model_name='simplefield',
            name='show_when_values',
            field=models.TextField(blank=True, help_text="One choice value (key) of the controlling field per line. This field is shown when the controlling field's answer is one of them.", verbose_name='show when values'),
        ),
    ]
